
<h1 style="text-align: center;">CIÊNCIA DE DADOS</h1>
<h1 style="text-align: center;">Roteiro de Atividade Prática</h1>
<br>
<br>

Nome: ______________________________________________________________________________________      

Turma: ______________


**Componente:** Matemática e Estatística para Ciência de Dados 
<br>
**Unidade Curricular:** Estatística Aplicada
<br>
**Tema da Semana:** Inferência Estatística: Testes de hipóteses parte II
<br>



# Aula 1

## Tarefa
- Execute o código abaixo.

- Se as bibliotecas não tiverem instaladas, instale-as.

- Acompanhe as instruções.

- Preencha o código onde está #TO DO

- Responda as perguntas e conclua a atividade


#### **Exercício 1: Teste de Proporção (Unilateral)**

Uma professora de Biologia quer avaliar se a proporção de estudantes interessados em participar de uma feira de ciências é maior do que 60%. Ela acredita que esse índice é o mínimo necessário para justificar a organização de um grande evento, envolvendo despesas consideráveis com estandes, materiais de laboratório e divulgação. Para verificar isso, preparou um questionário rápido que foi aplicado em todas as turmas do Ensino Médio, perguntando se os alunos “Gostariam” ou “Não gostariam” de participar ativamente de uma feira de ciências local.

Depois de consolidar as respostas, a professora obteve uma contagem de quantos alunos responderam positivamente e o total de questionários válidos. Seu objetivo é verificar se, do ponto de vista estatístico, podemos afirmar que a proporção de interessados na feira realmente ultrapassa o patamar de 60%. Se o resultado for favorável, a organização terá base para seguir em frente com os preparativos e buscar patrocínio. Se o resultado não for significativo, podem repensar estratégias de motivação ou divulgar melhor a importância de eventos científicos para a comunidade escolar.


In [3]:
import numpy as np
from statsmodels.stats.proportion import proportions_ztest

# Exemplo de valores coletados
contagem_interessados = 72  # Alunos interessados
total_alunos = 100
prop_esperada = 0.60

# Teste z para uma proporção (unilateral: H1 > 0.60)
estatistica, p_valor = proportions_ztest(count=contagem_interessados,
                                         nobs=total_alunos,
                                         value=prop_esperada,
                                         alternative='larger')

print("Estatística de teste:", estatistica)
print("p-valor:", p_valor)

alpha = 0.05
if p_valor < alpha:
    print("Rejeitamos H0. A proporção de interessados é maior que 60%.")
else:
    print("Não rejeitamos H0. Não há evidências de que a proporção seja maior que 60%.")


Estatística de teste: 2.6726124191242437
p-valor: 0.0037631575832289435
Rejeitamos H0. A proporção de interessados é maior que 60%.


#### **Perguntas: (responda com o professor)**

1. Por que utilizamos um teste unilateral aqui ao invés de bilateral?
    - Resposta: 
    
<br>

2. O que a professora pode concluir se o resultado não rejeitar H₀?
    - Resposta: 

<br>

---


#### **Exercício 2: Teste Pareado (Antes e Depois)**

O coordenador de um programa de reforço escolar em Matemática notou que alguns alunos tinham muita dificuldade na resolução de problemas que envolvem lógica e raciocínio abstrato. Para solucionar isso, introduziu uma técnica de ensino baseada em jogos de tabuleiro e desafios lógicos, aplicada em um grupo de 15 alunos por três semanas. Ele acredita que esse método ajuda a desenvolver habilidades de resolução de problemas de forma mais lúdica.

Para avaliar o impacto, o coordenador aplicou um teste de raciocínio antes do início do programa e repetiu o teste após as três semanas. O objetivo é verificar se houve aumento significativo na pontuação média desses alunos entre o “pré-teste” e o “pós-teste”. Se os resultados mostrarem melhora estatisticamente significativa, a escola poderá considerar implementar essa técnica de forma mais ampla em outras disciplinas. Caso contrário, deverão rever o material ou considerar outras metodologias que possam ser mais eficazes. A ideia é sempre usar recursos que tornem o aprendizado mais dinâmico, incentivando o aluno a pensar e resolver problemas de forma autônoma.

In [9]:
import numpy as np
from scipy.stats import ttest_rel

# Dados simulados: mesmas 15 pessoas antes e depois
antes = np.array([5, 6, 4, 5, 7, 6, 5, 4, 6, 5, 7, 8, 5, 6, 5])
depois = np.array([6, 7, 5, 6, 8, 7, 6, 5, 7, 6, 8, 9, 6, 7, 6])

# Teste t pareado (paired)
estatistica, p_valor = ttest_rel(antes, depois)

print("Estatística de teste:", estatistica)
print("p-valor:", p_valor)

alpha = 0.05
if p_valor < alpha:
    print("Rejeitamos H0. Há evidências de melhora significativa após a intervenção.")
else:
    print("Não rejeitamos H0. Não há evidências de melhora significativa.")

Estatística de teste: -inf
p-valor: 0.0
Rejeitamos H0. Há evidências de melhora significativa após a intervenção.


#### **Perguntas: (responda com o professor)**

1. Por que usar um teste pareado, ao invés de um teste para amostras independentes?
    - Resposta: 

<br>

2. Como a escola poderia agir se o p-valor fosse muito baixo?
    - Resposta: 


<br>

---

#### **Exercício 3: Teste de Independência (Qui-Quadrado)**

Em uma pesquisa sobre hábitos de leitura, um grupo de alunos montou um questionário para descobrir a relação entre o ano escolar (1º, 2º ou 3º do Ensino Médio) e o tipo de leitura preferida (livros de ficção, quadrinhos, jornais/revistas ou conteúdo digital na internet). Eles acreditam que a predileção por certo tipo de leitura possa variar conforme a maturidade acadêmica e a proximidade dos vestibulares e exames finais. Assim, construíram uma tabela de contingência relacionando a série em que o aluno se encontra e a forma de leitura mais frequente.

Depois de tabular as respostas, surgiu a dúvida: será que a preferência de leitura é independente do ano escolar, ou existe uma associação clara entre as duas variáveis? Para responder, decidiram aplicar o teste de independência baseado na distribuição qui-quadrado. Se constatarem que existe associação, podem direcionar ações específicas de incentivo à leitura, considerando as preferências de cada série. Se concluírem que não há associação, as estratégias de leitura poderão ser planejadas de forma mais geral, sem distinção de série.


In [15]:
import numpy as np
from scipy.stats import chi2_contingency

# Tabela de contingência (linhas: séries, colunas: tipo de leitura)
# Suponha que a pesquisa resultou em:
tabela = np.array([
    [15,  8,  5, 10],  # 1º ano
    [10, 15,  6, 14],  # 2º ano
    [ 8, 10,  7, 15]   # 3º ano
])

chi2, p_valor, dof, freq_esperada = chi2_contingency(tabela)

print("Estatística Qui-Quadrado:", chi2)
print("p-valor:", p_valor)
print("Graus de Liberdade:", dof)
print("Frequências Esperadas:\n", freq_esperada)

alpha = 0.05
if p_valor < alpha:
    print("Rejeitamos H0. Há evidências de que a preferência de leitura depende do ano escolar.")
else:
    print("Não rejeitamos H0. Não há evidências de associação entre a série e a preferência de leitura.")

Estatística Qui-Quadrado: 5.6577459820880875
p-valor: 0.46259962345596817
Graus de Liberdade: 6
Frequências Esperadas:
 [[10.19512195 10.19512195  5.56097561 12.04878049]
 [12.07317073 12.07317073  6.58536585 14.26829268]
 [10.73170732 10.73170732  5.85365854 12.68292683]]
Não rejeitamos H0. Não há evidências de associação entre a série e a preferência de leitura.


#### **Perguntas: (responda com seu professor)**


1. Por que o teste de qui-quadrado é apropriado para esse tipo de investigação?
    - Resposta: 


<br>

2. Se H₀ não for rejeitada, o que isso significa?
- Resposta: 

<br>

---

#### **Exercício 4: Teste Não Paramétrico (Mann-Whitney)**

Dois professores de Educação Física tiveram ideias diferentes para melhorar o condicionamento dos alunos: um deles propôs treinos intensivos de curta duração (HIIT), enquanto o outro preferiu treinos tradicionais de duração média e intensidade moderada. Para avaliar qual abordagem resultaria em melhor resistência física, eles aplicaram um teste de corrida com duração fixa de 12 minutos. O resultado mensurado seria a distância total percorrida em metros. Cada professor trabalhou com um grupo de alunos aleatórios, mas o primeiro grupo fez HIIT por quatro semanas, e o segundo grupo seguiu o método tradicional no mesmo período.

No entanto, alguns alunos do primeiro grupo apresentaram resultados muito distintos, pois eram acostumados a treinar intensamente fora da escola, enquanto outros do segundo grupo tinham restrições de saúde. Isso pode violar a suposição de normalidade dos dados. Assim, os professores decidiram utilizar um teste não paramétrico para comparar as performances dos dois grupos, pois esse tipo de teste não exige que as amostras sigam uma distribuição normal. Se o teste mostrar diferença significativa, o método de treino que resultar em melhor resistência poderá ser expandido para outras turmas. Caso contrário, podem analisar se a execução do programa foi uniforme ou se existem outros fatores (alimentação, motivação, descanso) que prejudicam a interpretação dos resultados.

In [19]:
import numpy as np
from scipy.stats import mannwhitneyu

# Dados simulados (distância em metros percorridos em 12 min)
grupo_HIIT = np.array([2100, 2500, 1950, 2200, 2800, 3000, 2600, 2300])
grupo_tradicional = np.array([2000, 1900, 2100, 2050, 2200, 2100, 2000, 2150])

estatistica, p_valor = mannwhitneyu(grupo_HIIT, grupo_tradicional, alternative='two-sided')

print("Estatística de teste:", estatistica)
print("p-valor:", p_valor)

alpha = 0.05
if p_valor < alpha:
    print("Rejeitamos H0. Há evidências de diferença significativa na resistência entre os métodos.")
else:
    print("Não rejeitamos H0. Não há evidências de diferença significativa entre os métodos.")

Estatística de teste: 53.5
p-valor: 0.02674387793966026
Rejeitamos H0. Há evidências de diferença significativa na resistência entre os métodos.


#### **Perguntas: (responda com seu professor)**


1. Por que escolher o teste Mann-Whitney ao invés de um teste t tradicional?
    - Resposta: 
    
<br>

2. O que significa concluir que não há diferença significativa entre os grupos, mesmo usando um teste não paramétrico?
    - Resposta:

<br>

---

#### Reflexões sobre a aula 1:

